// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZuCVyfSLgyd-t5MvsbkkdgHXy0MHeU7U',
    appId: '1:478006663361:web:7020c28a24d20cdcaa1c40',
    messagingSenderId: '478006663361',
    projectId: 'studenttaskmanager-d2422',
    authDomain: 'studenttaskmanager-d2422.firebaseapp.com',
    storageBucket: 'studenttaskmanager-d2422.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgYpjTIxXoVmtdiv5KOiQEU2R6mlsaWYU',
    appId: '1:478006663361:android:7d549da0ec7e0bd0aa1c40',
    messagingSenderId: '478006663361',
    projectId: 'studenttaskmanager-d2422',
    storageBucket: 'studenttaskmanager-d2422.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFsFdDcMqPDRCNLl6fJf76T8NBfur6bSs',
    appId: '1:478006663361:ios:19f34cce0139862daa1c40',
    messagingSenderId: '478006663361',
    projectId: 'studenttaskmanager-d2422',
    storageBucket: 'studenttaskmanager-d2422.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFsFdDcMqPDRCNLl6fJf76T8NBfur6bSs',
    appId: '1:478006663361:ios:19f34cce0139862daa1c40',
    messagingSenderId: '478006663361',
    projectId: 'studenttaskmanager-d2422',
    storageBucket: 'studenttaskmanager-d2422.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZuCVyfSLgyd-t5MvsbkkdgHXy0MHeU7U',
    appId: '1:478006663361:web:395b3bfcccb59313aa1c40',
    messagingSenderId: '478006663361',
    projectId: 'studenttaskmanager-d2422',
    authDomain: 'studenttaskmanager-d2422.firebaseapp.com',
    storageBucket: 'studenttaskmanager-d2422.firebasestorage.app',
  );
}
